version: '3.8'

services:
  # 1. Banco de Dados (MongoDB)
  db:
    image: mongo:4.4
    container_name: fatec-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - fatec-network

  # 2. Frontend (Node.js - Login/Cadastro)
  frontend:
    build: ./loginprogweb
    container_name: fatec-frontend-auth
    ports:
      - "3000:3000"
    environment:
      # Conecta no container 'db' e usa a mesma senha do Flask
      - MONGO_URI=mongodb://db:27017/login
      - JWT_SECRET=53D0jjbsjTb6Of+e0O>+na&p@UO0M!Z<_sUx.d*-c+ND
    depends_on:
      - db
    networks:
      - fatec-network

  # 3. Backend (Flask + Apache - Aplicação Principal)
  backend:
    build: ./web_server
    container_name: fatec-backend-app
    ports:
      - "5000:80"
    environment:
      - FLASK_RUN_HOST=0.0.0.0
    depends_on:
      - db
    networks:
      - fatec-network

networks:
  fatec-network:
    driver: bridge

volumes:
  mongo_data: